### ISSUE TITLE
PFH

### ISSUE THREAD

**Issue by senshi-x** [Krzmbrzl/CLib-ReferenceImplementation#1]
Hab den PFH mal ausprobiert (1:1 kopiert), bekomme damit

    21:07:38 Error in expression <_clientInit.sqf"
    diag_log("TEST");dfunc(triggercond)={private _playerpos=getpos>
    21:07:38   Error position: <(triggercond)={private _playerpos=getpos>
    21:07:38   Error Missing ;
    21:07:38 File OPT\OPT\addons\OPT\beam\fn_clientInit.sqf, line 1
    21:07:38 Error in expression <_clientInit.sqf"
    diag_log("TEST");dfunc(triggercond)={private _playerpos=getpos>
    21:07:38   Error position: <(triggercond)={private _playerpos=getpos>
    21:07:38   Error Missing ;
    21:07:38 File OPT\OPT\addons\OPT\beam\fn_clientInit.sqf, line 1
    21:07:39 (0) [CLib Log - Core]: Reading and Compiling all Function and Modules Required: 2911.000244140625 ms

Irgendeine spontane Idee? Dachte erst, dass die variablennamen schuld sind, deshalb haben die bei mir nicht mehr standardnamen.

**Comment by pmayd** [comment]
Brauche den Code, ansonsten steht ja klar dar, dass ein Semikolon Fehler vorliegt, also fehlt, demzufolge wird eine Anweisung unvollständig sein oder beim Kopieren ist was schief gelaufen, Fehler kann auch vorher schon vorgelegen haben, bei mir lief die Ref aber noch problemlos. Und das Makro wird ja keiner angefasst haben...

**Comment by senshi-x** [comment]
Code ist 1:1 aus https://github.com/Krzmbrzl/CLib-ReferenceImplementation/blob/master/addons/CLibRef/perFrame/fn_clientInit.sqf

Alternativ meine schon mit den anderen Variablennamen versehen:

https://github.com/WGPSenshi/OPT-Mod/blob/master/addons/OPT/Beam/fn_clientInit.sqf

Die Fehlermeldung kann ich schon auch lesen, aber mir ist eben kein fehlendes Semikolon aufgefallen :) .

**Comment by Krzmbrzl** [comment]
Der Code ist nicht eins zu eins kopiert... Bei dir fehlt das `#include`-statement (siehe https://github.com/Krzmbrzl/CLib-ReferenceImplementation/blob/master/addons/CLibRef/perFrame/fn_clientInit.sqf#L2). Deswegen findet er das Makro `DFUNC` nicht. Dementsprechend hast du nachher in deinem Code noch `DFUNC(triggerCond)` stehen, was einer invaliden SQF-Syntax entspricht. Und dafür ist die Standard-Fehlermeldung, dass ein Semikolon fehlen würde ;)
